// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { HealthApiHealthGetData, HealthApiHealthGetResponse, StartResearchApiResearchPostData, StartResearchApiResearchPostResponse, StartResearchApiResearchPostError, StreamResearchApiResearchSessionIdStreamGetData, StreamResearchApiResearchSessionIdStreamGetError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthApiHealthGetResponse, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};

/**
 * Start Research
 */
export const startResearchApiResearchPost = <ThrowOnError extends boolean = false>(options: Options<StartResearchApiResearchPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<StartResearchApiResearchPostResponse, StartResearchApiResearchPostError, ThrowOnError>({
        url: '/api/research',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Stream Research
 */
export const streamResearchApiResearchSessionIdStreamGet = <ThrowOnError extends boolean = false>(options: Options<StreamResearchApiResearchSessionIdStreamGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, StreamResearchApiResearchSessionIdStreamGetError, ThrowOnError>({
        url: '/api/research/{session_id}/stream',
        ...options
    });
};