// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ResearchRequest = {
    query: string;
};

export type ResearchResponse = {
    session_id: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type StartResearchApiResearchPostData = {
    body: ResearchRequest;
    path?: never;
    query?: never;
    url: '/api/research';
};

export type StartResearchApiResearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartResearchApiResearchPostError = StartResearchApiResearchPostErrors[keyof StartResearchApiResearchPostErrors];

export type StartResearchApiResearchPostResponses = {
    /**
     * Successful Response
     */
    200: ResearchResponse;
};

export type StartResearchApiResearchPostResponse = StartResearchApiResearchPostResponses[keyof StartResearchApiResearchPostResponses];

export type StreamResearchApiResearchSessionIdStreamGetData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/research/{session_id}/stream';
};

export type StreamResearchApiResearchSessionIdStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamResearchApiResearchSessionIdStreamGetError = StreamResearchApiResearchSessionIdStreamGetErrors[keyof StreamResearchApiResearchSessionIdStreamGetErrors];

export type StreamResearchApiResearchSessionIdStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};
